version: '3.8'

services:
  backend:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=endpoints.py
    command: flask run --host=0.0.0.0

  frontend:
    build: ./block-explorer
    volumes:
      - ./block-explorer:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: npm start

volumes:
  node_modules:
